-- 遠征管理機能用マイグレーション

CREATE TABLE expeditions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  base_fee INT NOT NULL DEFAULT 0,
  pre_night_fee INT NOT NULL DEFAULT 0,
  lunch_fee INT NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE expedition_participants (
  id INT AUTO_INCREMENT PRIMARY KEY,
  expedition_id INT NOT NULL,
  member_id INT NOT NULL,
  pre_night TINYINT(1) NOT NULL DEFAULT 0,
  lunch TINYINT(1) NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'confirmed',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (expedition_id) REFERENCES expeditions(id) ON DELETE CASCADE
);

CREATE TABLE expedition_cars (
  id INT AUTO_INCREMENT PRIMARY KEY,
  expedition_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  capacity INT NOT NULL DEFAULT 5,
  rental_fee INT NOT NULL DEFAULT 0,
  highway_fee INT NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (expedition_id) REFERENCES expeditions(id) ON DELETE CASCADE
);

CREATE TABLE expedition_car_members (
  id INT AUTO_INCREMENT PRIMARY KEY,
  car_id INT NOT NULL,
  member_id INT NOT NULL,
  role ENUM('driver','sub_driver','passenger') NOT NULL DEFAULT 'passenger',
  is_excluded TINYINT(1) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (car_id) REFERENCES expedition_cars(id) ON DELETE CASCADE
);

CREATE TABLE expedition_car_payers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  car_id INT NOT NULL,
  member_id INT NOT NULL,
  amount INT NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (car_id) REFERENCES expedition_cars(id) ON DELETE CASCADE
);

CREATE TABLE expedition_teams (
  id INT AUTO_INCREMENT PRIMARY KEY,
  expedition_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (expedition_id) REFERENCES expeditions(id) ON DELETE CASCADE
);

CREATE TABLE expedition_team_members (
  id INT AUTO_INCREMENT PRIMARY KEY,
  team_id INT NOT NULL,
  member_id INT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (team_id) REFERENCES expedition_teams(id) ON DELETE CASCADE
);

CREATE TABLE expedition_collections (
  id INT AUTO_INCREMENT PRIMARY KEY,
  expedition_id INT NOT NULL,
  round TINYINT NOT NULL DEFAULT 1,
  title VARCHAR(255) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (expedition_id) REFERENCES expeditions(id) ON DELETE CASCADE
);

CREATE TABLE expedition_collection_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  collection_id INT NOT NULL,
  member_id INT NOT NULL,
  amount INT NOT NULL DEFAULT 0,
  paid TINYINT(1) NOT NULL DEFAULT 0,
  memo VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (collection_id) REFERENCES expedition_collections(id) ON DELETE CASCADE
);

CREATE TABLE expedition_tokens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  expedition_id INT NOT NULL,
  token VARCHAR(64) NOT NULL UNIQUE,
  expires_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (expedition_id) REFERENCES expeditions(id) ON DELETE CASCADE
);

CREATE TABLE expedition_booklets (
  id INT AUTO_INCREMENT PRIMARY KEY,
  expedition_id INT NOT NULL UNIQUE,
  items JSON,
  published TINYINT(1) NOT NULL DEFAULT 0,
  public_token VARCHAR(64),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (expedition_id) REFERENCES expeditions(id) ON DELETE CASCADE
);
